#!/usr/bin/env bash
# Install the web server 'nginx' on the server
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
if dpkg -l | grep -q 'nginx'; then
	sudo sed -i 's/listen 80;/listen 80;/' /etc/nginx/sites-available/default
	sudo sed -i 's@try_files $uri $uri/ =404;@return 200 \"Hello World!\\n\";@' /etc/nginx/sites-available/default
	sudo service nginx restart
fi
