#!/usr/bin/env bash
#Installs nginx on my server

sudo apt-get upgrade
sudo apt-get -y install nginx
sudo sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
sudo sed -i 's@try_files $uri $uri/ =404;@return 200 "Hello World!\n";@' /etc/nginx/sites-available/default
sudo service nginx restart
