#!/usr/bin/env bash
# Install the web server 'nginx' on the server
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
if dpkg -l | grep -q 'nginx'; then
	sudo ufw allow "Nginx HTTP"
	sudo echo "Hello World!\n" > /var/www/html/index.nginx-debian.html
	sudo service nginx start
fi
