#!/usr/bin/env bash
# Install the web server 'nginx' on the server
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
if dpkg -l | grep -q 'nginx'; then
	sudo ufw allow "Nginx HTTP"
	echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
	echo "server {
			listen 80 default_server;
       			listen [::]:80 default_server;

			root /var/www/html;
			index index.html index.htm index.nginx-debian.html;
			error_page 404 /404.html

			server_name _;
			location / {
				try_files \$uri \$uri/ =404;
			}

			location /redirect_me {
				return 301 \"https://google.com\";
			}
	}" | sudo tee /etc/nginx/sites-available/default > /dev/null
	sudo service nginx start
fi
