#!/usr/bin/env bash
# Change your home IP

#Create a temp file
tempF=$(mktemp)

#Modify the hosts file and save it in the temp file
sed 's/127.0.0.1/127.0.0.2/' /etc/hosts > "$tempF"
echo "8.8.8.8 facebook.com" >> "$tempF"
cp "$tempF" /etc/hosts

#Clean away the temp file
rm "$tempF"
